### ISSUE TITLE
MiInspector: bug displaying with FamixStAnnotationType

### ISSUE THREAD

**Issue by NicolasAnquetil** [moosetechnology/Midas#114] opened 2021-05-03 09:59 UTC
Create a Famix model including methods with pragma (e.g. all Rubric packages)

Find one FamixStInstanciationType

Inspect it: Error with MiTreeBrowser

**Comment by NicolasAnquetil** [comment] 2021-05-03 10:26
The bug also appears for other kinds of entities (ex: FamixStGlobalVariable, FamixStMethod)

**Comment by jordanmontt** [comment] 2021-05-29 00:57
I cannot reproduce this anymore. Can you @NicolasAnquetil ? Or should we close this issue?

**Closed** 2021-06-01 18:47 UTC
Labels: bug
