### ISSUE TITLE
Overview browser lacks a scroll bar

### ISSUE THREAD

**Issue by NicolasAnquetil** [moosetechnology/Midas#84] opened 2020-07-20 10:17 UTC
When there are too many browser, the last ones are not visible/accessible

**Comment by jordanmontt** [comment] 2021-04-30 13:54
I testes it in it is working fine for my. I opened a large number of browsers and I get the scrollbar. 
See:
![image](https://user-images.githubusercontent.com/33934979/116704929-7dd4ab00-a9bb-11eb-89c5-8f57b600e810.png)

**Comment by jordanmontt** [comment] 2021-06-01 14:20
I will close this because I was not able to reproduce this

**Closed by jordanmontt** 2021-06-01 14:20 UTC
Labels: Sprint
